### ISSUE TITLE
Skipped exercises continues to run in background

### ISSUE THREAD

**Issue by rsiccho** [scoute-dich/Sieben#18]
Hi,

I have a massive problem since (I guess) version 1.5
Everytime I want to skip an exercise then new exercise appears correctly with the pause, but, in the background, the old continues. When I skip several exercises, all skipped are running in the background. You can hear the name of the exercise and so on. The only chance I have is to kill the application.
I can send you a video when it helps.

**Comment by scoute-dich** [comment]
Sorry for the late answer, I was in holidays ;-)

I released a new version today with a few bug fixes. I don't have your problem on the current version. Also no other users did report something...

Perhaps it's the best to uninstall seven and make a new install. Please try it and report back...

Greetings
Gaukler Faun

**Comment by scoute-dich** [comment]
Is your issue solved with latest update and a fresh install? Please give feedback.

**Comment by rsiccho** [comment]
Hi,
No. The issue is not solved for me.

**Comment by scoute-dich** [comment]
Strange I can't reproduce it. On my phone it works like it should. Did you uninstall and reinstall the app?

**Comment by rsiccho** [comment]
Yes I uninstalled and reinstalled it.
Today I installed it on my phone and there it was working fine. Both are LG devices. Tablet runs with Android 4.4.2 and Phone with Android 6.
Maybe I find some time in the near future to debug the problem. Currently I'm in stress and have no Android Studio present to do this shortly.

**Comment by scoute-dich** [comment]
Then I think android 4.4.2 is the problem. I only have Lollipop and Marshmallow devices to test. I will look for a solution, when I have more time.

**Comment by scoute-dich** [comment]
I just released a new update with a possible fix. I replaced all finish() methods with finish Acitivity(). Let's see if it helps. Please report back after update.

**Comment by rsiccho** [comment]
The update came some minutes ago. Now there is no possibility to switch to the second exercise. After the countdown is finished and "Geschafft" is displayed, there is no possibility to jump to the next exercise.

**Comment by scoute-dich** [comment]
Have you checked in settings the exercises you want to perform? On my phone the app is fully functional (cm13, marshmallow).

**Comment by scoute-dich** [comment]
P.S.: The swipe area is only over the exercise image.

**Comment by rsiccho** [comment]
After several uninstall and install proceedings the original issue is back. So I don't get the "Geschafft", but skipping an exercise is still not working correctly.
I added a video in a zip file for showing the problem.
In the video I started the app, show the settings that everything is okay and then switch to exercise 4. After that I didn't touch the device. You see that the activities aren't exited correctly, they are still running. After the countdown in one activity ended they appear in the screen.
[sieben.zip](https://github.com/scoute-dich/Sieben/files/348366/sieben.zip)

**Comment by rsiccho** [comment]
Just installed the app on a Samsung G1 with CM11 (Android 4.4.4) same issue like the tab. So I guess the Android 4.4 is the problem.

**Comment by scoute-dich** [comment]
Hi,

I watched the attached video - strange. I set all new intents to "intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);" now. Perhaps It helps. I attached a apk file with the new code in the zip file. Perhaps you can install and test it, before I release an update?

Regards
Gaukler Faun
[app-release.zip](https://github.com/scoute-dich/Sieben/files/381324/app-release.zip)

**Comment by rsiccho** [comment]
Hi,
I installed the apk, but no improvement on that device. The issue is still there.
In the meantime I installed the AndroidStudio and imported the project. I did some code changes, but had also no luck at fixing the issue. Hopefully I have some more time in the next weeks, so that I can have a deeper look to what is going on at the device. I would report any useful informations here, when I'm successful.

**Comment by scoute-dich** [comment]
Ok, thanks for your efforts.

**Comment by YoungNFoolish** [comment]
Hi,
I have the same problem on Galaxy S3 api 17 (android 4.2.2). Actually paused or skipped exercise's timer continues to run in the background.

Sorry for my bad english!

**Comment by StarvingMarvin** [comment]
I'm having the same issue on HTC One M8, Running Cyanogen Mod 11 (Android 4.4.4)

**Comment by scoute-dich** [comment]
Ok, I will take a look in autumn vacations. At the moment I'm busy at school... Of anyone has an idea, just tell me...

**Comment by scoute-dich** [comment]
I only have a device with lollipop, so it's difficult for me to test.

**Comment by scoute-dich** [comment]
Can someone test the attached, zip compressed apk file?
[app-release.apk.zip](https://github.com/scoute-dich/Sieben/files/564050/app-release.apk.zip)

**Comment by StarvingMarvin** [comment]
Just tried it. Same problem

**Comment by rsiccho** [comment]
Finally, it seems that I found a solution. The cancel() call in the onTick-method is not working. I added a lot of logoutput in all the methods an saw, that it is not cancelling properly. Using a patched CountDownTimer that can handle cancel calls from Timer thread worked for me. Here is the solution from stackoverflow [http://stackoverflow.com/questions/6423848/countdowntimer-cancel-is-not-working-in-android](url)
After changing all imports to the patched Timer, it is correctly cancelled and the app works again.

**Comment by scoute-dich** [comment]
Thanks a lot. So I should create the "new" countdown timer class and then change all imports in the activities? That's all?

**Comment by rsiccho** [comment]
Yes, it worked for me. I made also some huge refactorings to get rid of the massive duplicated code and to drill down the issue, that's why I can't contribute it here to github.

**Comment by scoute-dich** [comment]
Thanks to @rsiccho here a new attempt. Please can someone test it and when the issue is solved I will release an update.

[app-release.apk.zip](https://github.com/scoute-dich/Sieben/files/573930/app-release.apk.zip)

**Comment by rsiccho** [comment]
Looks good, the issue is gone!

**Comment by scoute-dich** [comment]
Ok. Thanks for testing and again for your investigations.
